Update Update-AzCosmosDBAccountFailoverPriority.md
The command mentioned in this document is - Update-AzCosmosDBAccountFailoverPriority -ResourceGroupName rg -Name dbname -FailoverPolicy "region1, region2, region3"
When I tried to execute the command in the below format, it is throwing parse exception.

Update-AzCosmosDBAccountFailoverPriority -ResourceGroupName RGName -Name AcctName -FailoverPolicy "East US, West US, South Central US"

Exception: Update-AzCosmosDBAccountFailoverPriority : Unable to parse request payload. 
ActivityId: 3e7d885b-e04a-485f-a0ae-c43e77680153, Microsoft.Azure.Documents.Common/2.11.0
At line:1 char:2
+  Update-AzCosmosDBAccountFailoverPriority -ResourceGroupName Mig -Nam ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzCosmosDBAccountFailoverPriority], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.CosmosDB.UpdateAzCosmosDBAccountFailoverPriority

As per my understanding the argument -FailoverPolicy needs to be passed as an array. In the example given in the document it seems to be passed as string rather than array. So I modified the script as below by passing the argument as an array and it worked as expected.

Working Command:
Update-AzCosmosDBAccountFailoverPriority -ResourceGroupName RGName -Name AccntName -FailoverPolicy @("South Central US","East US","West US").

Initially this issue reported from Walmart and I have validated it my end too.

Request you to validate this change before we get some noise from customers.